---
- name: image building dependence
  dnf:
    name:
      - curl
      - expect
      - sed
      - tar
      - qemu-kvm
      - virt-install
      - libvirt-daemon-kvm
    state: latest
  become: yes
  register: dnf_result
  until: dnf_result is success
  retries: 5
  delay: 60

- name: generate ks file for image_maker
  template:
    src: "{{ os }}-{{ arch }}-ks.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"

- name: copy virt-install-image shell script to image_maker
  copy:
    src: "files/virt-install-image"
    dest: "/home/fedora/virt-install-image"
    mode: '0764'

- name: build qcow2 image first
  command: /home/fedora/virt-install-image /home/fedora/{{ os }}_{{ arch }}.qcow2 {{ os }}_{{ arch }}.ks {{ repos[os]["baseos"] }}

- name: fetch image back
  fetch:
    src: "/home/fedora/{{ os }}_{{ arch }}.qcow2"
    dest: "{{ playbook_dir }}/"
    validate_checksum: yes
    flat: yes
