---
- name: create keypair for rhel-edge test
  openstack.cloud.keypair:
    cloud: rhos-01
    state: present
    name: rhel-edge
    public_key_file: key/ostree_key.pub

- name: create security group for ssh only
  openstack.cloud.security_group:
    cloud: rhos-01
    name: ssh_only
    state: present
    description: security group for ssh only

- name: permit ssh in security group ssh_only
  openstack.cloud.security_group_rule:
    cloud: rhos-01
    security_group: ssh_only
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: set openstack instance name
  set_fact:
    instance_name: "edge-{{ os }}-image-maker"

- name: deploy instance
  openstack.cloud.server:
    cloud: rhos-01
    name: "{{ instance_name }}"
    image: Fedora-Cloud-Base-34
    flavor: ci.standard.large
    network: shared_net_9
    key_name: rhel-edge
    security_groups: ssh_only
    auto_ip: yes
    config_drive: yes
    wait: yes
    timeout: 600
    userdata: |
      #!/bin/bash
      dnf -y install python3-dnf python3
  register: instance_result

- name: waits until instance is reachable
  wait_for:
    host: "{{ instance_result.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
    delay: 10

- name: add os instance ip into host group image_maker
  add_host:
    name: "{{ instance_result.openstack.public_v4 }}"
    groups: builder

- name: keep private key permission to 600
  file:
    path: key/ostree_key
    mode: 0600

- name: ensure cloud-init has finished
  raw: test -f /var/lib/cloud/instance/boot-finished
  retries: 60
  register: cloud_init_check
  changed_when: false
  until: cloud_init_check is success
  delegate_to: "{{ instance_result.openstack.public_v4 }}"
