---
name: Lint

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: "🔭 Shellcheck"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@0.5.0
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2002

  yamllint:
    name: "🔬 yamlint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
